display list of previous tasks in the order it finished
avelynhc/time_tracker pull request #42
Opened 2022-06-01 12:20 UTC by avelynhc

- `task_detail` page now can display the tasks in descending order
- change the finish_time of unfinished task to 0 to compare the value of finish_time between the tasks in `task_detail.py` in backend by using `sort` function

2022-06-03 17:52 UTC, lyndonoc requested changes
one comment

2022-06-03 17:52 UTC, lyndonoc commented on backend/resources/task_detail.py
> +            task_list.sort(key=lambda x: x.get("finish_time"))
can we sort by start_time instead and use the database's sort instead of sorting this manually?

2022-06-05 10:14 UTC, avelynhc commented
- I changed the way tasks are displayed based on start_time using database's sort as per your request
- pr for logout and adding /new are accidently added, please review those as well
- Gracias!

2022-06-14 04:36 UTC, lyndonoc approved these changes
LGTM

2022-06-21 06:12 UTC, merged